language: python
python:
  - "2.7"
# install dependencies
#install: pip install
install: pip install behave
install: python setup.py install
# run tests
# script: nosetests
script: python setup.py test
